# Generated by Django 3.1.14 on 2022-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20221128_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_eng',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
