# Generated by Django 3.1.14 on 2022-11-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20221129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_evolutionnext_evol', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
